version: '3'

services:
  db:
    image: mariadb:10
    ports:
      - '3306:3306'
    volumes:
      - ./Dockerdir/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: office-management

volumes:
  db-storage:
